var table = 
{
    0: [["oi", "ola", "olá"]],
    1: [["teste", "testando"]],
    2: [["quando", "onde"], ["abaco", "ábaco"], ["surgiu", "criado", "inventado", "desenvolvido"]],
    3: [["quando", "onde"], ["primeiro"], ["surgiu", "criado", "inventado", "desenvolvido"], ["equipamento", "objeto", "aparato"], ["contar", "conta", "contas"]],
    4: [["qual"], ["primeiro"], ["equipamento", "objeto", "aparato"], ["contar", "conta", "contas"]],
    5: [["que", "qual"], ["significado", "significa", "origem"], ["computador"]],
        6: [["quem", "quando", "qual", "onde"], ["surgiu", "criou", "criada", "inventou", "inventada", "desenvolveu", "desenvolvida", "construida", "construiu", "nome"], ["primeira"], ["calculadora", "contas"]],
    7: [["quando", "quem", "onde"], ["surgiu", "criou", "criado", "inventou", "inventado", "desenvolveu", "desenvolvido", "construido", "construiu"], ["primeiro"], ["computador"], ["eletromecânico", "eletromecanico"]],
    8: [["quem"], ["criou", "inventou", "desenvolveu", "escreveu"], ["primeiro"], ["compilador"]],
        9: [["quem", "onde", "qual"], ["surgiu", "criou", "criado", "inventou", "inventado", "desenvolveu", "desenvolvido", "construido", "construiu", "nome"], ["primeiro"], ["computador"]],
        10: [["que", "qual"], ["significa", "significado", "dizer"], "eniac"],
        11: [["quando"], ["surgiu", "criado", "inventado", "desenvolvido"], ["primeiro"], ["computador"], ["arquitetura"], ["von"], ["neumann"]],
        12: [["quando"], ["surgiu", "criada", "inventada", "desenvolvida"], ["arquitetura"], ["von"], ["neumann"]],
        13: [["que", "quais"], ["é", "são"], ["caracteristicas", "características", "arquitetura"], ["arquitetura"], ["von"], ["neumann"]],
        14: [["quando", "quem"], ["surgiu", "criou", "criado", "inventou", "inventado", "desenvolveu", "desenvolvido", "construido", "construiu", "lançou", "lançado"], ["primeiro"], ["computador"], ["comercial"]],
        15: [["que"], ["é", "são"], ["circuitos", "circuito"], ["integrados", "integrado"]],
        16: [["quem", "quando"], ["surgiu", "criou", "criado", "inventou", "inventado", "desenvolveu", "desenvolvido"], ["circuitos", "circuito"], ["integrados", "integrado"]],
        17: [["que"], ["é", "são"], ["programa", "programas"]],
        18: [["que"], ["são", "é"], ["instruções", "instrução"], ["maquina"]],
        19: [["que"], ["é"], ["ula"]],
        20: [["que"], ["é"], ["unidade"], ["lógica", "logica"], ["aritmética"]],
        21: [["que"], ["são", "é"], ["registradores", "registrador"]],
        22: [["que"], ["é"], ["unidade"], ["controle"]],
        23: [["que"], ["é"], ["cpu"]],
        24: [["que"], ["compõe", "compoe"], ["computador"]],
        25: [["que"], ["é"], ["sistema"], ["armazenamento"]],
        26: [["que"], ["são"], ["dispositivos"], ["entrada", "entradas"], ["saída", "saida", "saídas", "saidas"]],
        27: [["que"], ["é", "são"], ["microprocessadores", "microprocessador"]]
};

var tableNames =
{
        0: "Olá.",
        1: "ChatBot em funcionamento.",
        2: "Entre 3000 e 500 AC, na Babilônia.",
        3: "Entre 3000 e 500 AC, na Babilônia.",
        4: "O ábaco",
        5: 'A palavra COMPUTADOR vem de "compto", que pode ser definido como uma ferramenta para fazer contas.',
        6: "A primeira calculadora mecânica do mundo, La pascaline, foi construida em 1642 na França, pelo físico e matemático Blaise Pacal.",
        7: "Konrad Zuse desenvolveu, entre 1936 e 1941, na Alemanha, os primeiros computadores eletromecânicos, chamados: Z1, Z2, Z3 e Z4.",
        8: "Grace Hopper.",
        9: "O ENIAC foi construído pelo professor John Mauchly e por John Eckert na Universidade da Pensilvânia – EUA.",
        10: 'ENIAC, significa "Electronic Numerical Integrator And Computer".',
        11: "O IAS foi o primeiro computador construido com a arquitetura de von Neumann.",
        12: "O IAS foi o primeiro computador construido com a arquitetura de von Neumann.",
        13: "A arquitetura de von Neumann é caracterizada pelo hardware fixo e genérico e ainda é utilizada na construção dos computadores atuais.",
        14: "O primeiro computador comercial foi lançado por Eckert e Mauchly em 1947.",
        15: "São circuitos cujos transistores estão em um único componente.",
        16: "Os circuitos integrados foram inventados por Jack Killby, em 1958.",
        17: "Um programa é uma sequência de instruções que realizam uma determinada tarefa.",
        18: "instruções de maquina são instruções básicas quee são as únicas funções que um computador consegue entender.",
        19: "É um dos tres blocos que compõem a CPU, ela é encarregada de executar todas as operações lógicas e aritméticas",
        20: "É um dos tres blocos que compõem a CPU, ela é encarregada de executar todas as operações lógicas e aritméticas",
        21: "Um dos tres blocos que compõem a CPU, o registrador é a unidade de armazenamento mais básica, tanto para dados que serão processados, como para os dados resultantes desse processamento",
        22: "É um dos tres blocos que compõem a CPU, ele controla a perfeita execução das sequências de intruções (programa), garantindo o sincronismo e a ordenação de cada passo; bem como, interpretando e gerando sinas de controle extrenos à CPU",
        23: "A CPU - Central Processing Unit é o componente principal de um computador.",
        24: "Um computador é composto pela CPU interligada a um sistema de armazenamento e a dispositivos de entrada e saida.",
        25: "Ele é constituido pela memória RAM, onde ficam instruções (programas) e dados, e de dispositivos externos como discos rígidos (HD), ópticos (CD e DVD) e dispositivos de memória Flash (pen drives e cartões de memória).",
        26: "São dispositivos que permitem a internalização de dados, para armazenamento ou, processamento; a externalização dos resultados e o acesso aos dados armazenados. Alguns exemplos são: placa de vídeo, teclado, monitor.",
        27: "Os microprocessadores são circuitos integrados que abrigam em seu encapsulamento uma CPU completa. Posteriormente foram incorporados memória cache e outros circuitos como controladores de E/S e de memória."
};